# Generated by Django 6.0 on 2025-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='price',
            new_name='monthly_rent',
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hostel',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
